blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    path('',views.post_list,name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('<int:post_id>/share/',views.post_share,name='post_share')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('home/', include('start.urls', namespace='start')),
    path('', include('start.urls', namespace='start')),
]

start/urls.py
from django.urls import path
from . import  views

app_name = 'start'

urlpatterns = [
    # home view
    path('',views.home_display,name='home_display')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post (models.Model):
    STATUS_CHOICES = (('draft','Draft'),('published','Published'),)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,default='draft')
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[self.publish.year,self.publish.month,self.publish.day, self.slug])


class Kommentar (models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

start/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from .models import Kommentar

class EmailPostForm (forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Kommentar
        fields = ('name','email','body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.core.mail import send_mail
from .models import Post, Kommentar
from .forms import EmailPostForm, CommentForm

# Create your views here.
def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3) # 3 posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer return the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range return the last page
        posts = paginator.page(paginator.num_pages)
    return render (request,'blog/post/list.html',{'page':page,'posts':posts})

def post_detail(request,year,month,day,post):
    post = get_object_or_404(Post,slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment object but do not save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    #sent = False
    return render (request,'blog/post/detail.html',{'post':post,
                                                    'comments':comments,
                                                    'new_comment': new_comment,
                                                    'comment_form': comment_form})

def post_share (request,post_id):
    post = get_object_or_404(Post,id=post_id,status='published')
    sent=False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject,message,'email.tpolzerwebsite@gmail.com',[cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request,'blog/post/share.html',{'post':post,'form':form,'sent':sent})

start/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import RequestContext,loader,Context

# Create your views here.
def home_display(request):
    return render(request, 'start/index.html')

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>My blog</h2>
    <p>This is my blog.</p>
  </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "basis.html" %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|linebreaks }}
  <p>
    <a href="{% url "blog:post_share" post.id %}">Share this post</a>
  </p>
  {% with comments.count as total_comments %}
  <h2>
    {{ total_comments }} comment{{ total_comments | pluralize }}
  </h2>
  {% endwith %}
{% for comment in comments %}
  <div class="comment">
    <p class="info">
      Comment {{ forloop.counter }} by {{ comment.name }}
      {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
  </div>
{% empty %}
 <p>There are no comments yet</p>
{% endfor %}

{% if new_comment %}
<h2 class="bg-success text-white">Your comment has been added</h2>
{% else %}
<h2>Add a new comment</h2>
<form method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>
{% endif %}


{% endblock %}

blog/templates/blog/post/list.html
{% extends "basis.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}

  <h1>My Blog</h1>
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}

{% with page=posts %}
{% include "pagination.html" %}
{% endwith %}

{% endblock %}

blog/templates/blog/post/share.html
{% extends "basis.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
    <h1>Email successfully sent</h1>
    <p>
        "{{post.title}}" was successfully sent to {{form.cleaned_data.to}}.
    </p>
    {% else %}
        <h1>Share "{{post.title}}" by Email</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send Email">
        </form>
    {% endif %}
{% endblock %}

blog/templates/pagination.html
<!--Bootstrap pagination combined with Django pagination -->
<nav aria-label="Page navigation blogs">
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{page.previous_page_number}}">Vorherige Seite</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="?page=1">Vorherige Seite</a></li>
    {% endif %}
    {% for curr_page in page.paginator.page_range %}
    {% if curr_page == page.number %}
    <li class="page-item active"><a class="page-link" href="?page={{curr_page}}">{{curr_page}}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{curr_page}}">{{curr_page}}</a></li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{page.next_page_number}}">Nächste Seite</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="?page={{page.paginator.num_pages}}">Nächste Seite</a></li>
    {% endif %}
  </ul>
</nav>

start/templates/start/index.html
{% extends "basis.html" %}

{% block title %}Startseite{% endblock %}

{% block content %}

<!-- Carousel -->
<div id="demo" class="carousel slide mt-1" data-ride="carousel">
<!--Indicators-->
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>
<!--The slideshow-->
  <div class="carousel-inner rounded">
    <div class="carousel-item active">
        {% load static %}
      <img src="{% static "img/Falaises_Agde.jpg" alt="Cap d'Agde Klippen" %}">
        <div class="carousel-caption">
          <h3>Le Cap d'Agde</h3>
          <p>Die Meeresklippen.</p>
        </div>
    </div>
    <div class="carousel-item">
      <img src="{% static "img/Falaises2_Agde.jpg" alt="Cap d'Agde Klippen" %}">
        <div class="carousel-caption">
          <h3>Le Cap d'Agde</h3>
          <p>Blick nach Südwesten.</p>
        </div>
    </div>
    <div class="carousel-item">
      <img src="{% static "img/CentrePort.jpg" alt="Cap d'Agde Yachthafen" %}">
        <div class="carousel-caption">
          <h3>Le Cap d'Agde</h3>
          <p>Der Yachthafen.</p>
        </div>  
    </div>
  </div>
<!--Left and right controls-->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>
<!-- End of Carousel -->

{% endblock %}

templates/basis.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Thomas Polzer</title>
  <meta charset="utf-8">
    {% load static %}
  <link rel="stylesheet" href="{% static  "lib/bootstrap-4.5.2-dist/css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static  "css/settings.css" %}">
  <script src="{% static  "lib/jquery/jQuery.js" %}"></script>
  <script src="{% static  "lib/popper/popper.min.js" %}"></script>
  <script src="{% static  "lib/bootstrap-4.5.2-dist/js/bootstrap.min.js" %}"></script>
   <style>
  /* Make the image fully responsive */
  .carousel-inner img {
    width: 100%;
    height: 100%;
  }
  </style>
</head>
<body>
<!-- entire container -->
<div class="container pt-1">

<!-- Navigation bar -->

<nav class="navbar navbar-expand-sm bg-dark navbar-dark rounded">
  <!-- Brand -->
  <a class="navbar-brand" href="#">Logo</a>

  <!-- Links -->
  <ul class="navbar-nav">

  <!-- Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Südfrankreich
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Agde</a>
        <a class="dropdown-item" href="#">Béziers</a>
        <a class="dropdown-item" href="#">Sète</a>
        <a class="dropdown-item" href="#">Pézenas</a>
        <a class="dropdown-item" href="#">Arrière-Pays</a>
      </div>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="/blog">Blogs</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Machine Learning</a>
    </li>


  </ul>

<!--   search field, aligned to the right  -->
  <form class="form-inline ml-auto" action="/action_page.php">
    <input class="form-control mr-sm-2" type="text" placeholder="Search">
    <button class="btn btn-success" type="submit">Search</button>
  </form>

</nav>

<!-- end of Navigation bar -->


{% block content %}
<!-- Carousel -->
<!--<div id="demo" class="carousel slide mt-1" data-ride="carousel">
  &lt;!&ndash; Indicators &ndash;&gt;
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>
  &lt;!&ndash; The slideshow &ndash;&gt;
  <div class="carousel-inner rounded">
    <div class="carousel-item active">
      <img src="{% static "img/Falaises_Agde.jpg" alt="Cap d'Agde Klippen" %}">
    </div>
    <div class="carousel-item">
      <img src="{% static "img/Falaises2_Agde.jpg" alt="Cap d'Agde Klippen" %}">
    </div>
    <div class="carousel-item">
      <img src="{% static "img/CentrePort.jpg" alt="Cap d'Agde Yachthafen" %}">
    </div>
  </div>
  &lt;!&ndash; Left and right controls &ndash;&gt;
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>-->
<!-- End of Carousel -->

<!-- end of entire container -->

{% endblock %}

</div>


</body>
</html>